#ifndef VERSION_H
#define VERSION_H

#define ALG_WELCOME_VERSION "2.1.11"
#define ALG_WELCOME_VERSION_MAJOR 2
#define ALG_WELCOME_VERSION_MINOR 1
#define ALG_WELCOME_VERSION_PATCH 8

#endif // VERSION_H
