#ifndef VERSION_H
#define VERSION_H

#define ALG_WELCOME_VERSION "3.0.1"
#define ALG_WELCOME_VERSION_MAJOR 3
#define ALG_WELCOME_VERSION_MINOR 0
#define ALG_WELCOME_VERSION_PATCH 1

#endif // VERSION_H
