// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentTheme() {
  return window['go']['main']['App']['CurrentTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MirrorList(arg1) {
  return window['go']['main']['App']['MirrorList'](arg1);
}

export function ToggleTheme(arg1) {
  return window['go']['main']['App']['ToggleTheme'](arg1);
}

export function UpdateSystem() {
  return window['go']['main']['App']['UpdateSystem']();
}
