// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists() {
  return window['go']['main']['App']['CheckFileExists']();
}

export function CurrentTheme() {
  return window['go']['main']['App']['CurrentTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsLiveISO() {
  return window['go']['main']['App']['IsLiveISO']();
}

export function LogMessage(arg1) {
  return window['go']['main']['App']['LogMessage'](arg1);
}

export function MirrorList(arg1) {
  return window['go']['main']['App']['MirrorList'](arg1);
}

export function RunCalamaresIfLiveISO() {
  return window['go']['main']['App']['RunCalamaresIfLiveISO']();
}

export function ScreenResolution() {
  return window['go']['main']['App']['ScreenResolution']();
}

export function StartLogging(arg1) {
  return window['go']['main']['App']['StartLogging'](arg1);
}

export function ToggleAutostart(arg1) {
  return window['go']['main']['App']['ToggleAutostart'](arg1);
}

export function ToggleTheme(arg1) {
  return window['go']['main']['App']['ToggleTheme'](arg1);
}

export function URL(arg1) {
  return window['go']['main']['App']['URL'](arg1);
}

export function UpdateSystem() {
  return window['go']['main']['App']['UpdateSystem']();
}
