// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists():Promise<boolean>;

export function CurrentTheme():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsLiveISO():Promise<boolean>;

export function LogMessage(arg1:string):Promise<void>;

export function MirrorList(arg1:string):Promise<void>;

export function RunCalamaresIfLiveISO():Promise<void>;

export function ScreenResolution():Promise<void>;

export function StartLogging(arg1:string):Promise<void>;

export function ToggleAutostart(arg1:boolean):Promise<void>;

export function ToggleTheme(arg1:boolean):Promise<void>;

export function URL(arg1:string):Promise<void>;

export function UpdateSystem():Promise<void>;
